first_word = input("Enter first word: ")
first_color = input("Enter first color: ")
second_word = input("Enter first word: ")
second_color = input("Enter first color: ")
endihg = input("Enter ending: ")
print(f"{first_word} are {first_color}")
print(f"{second_word} are {second_color}")
print(f"{endihg}")